# Colors (The Love Lace Custom)

# Default colors
[colors.primary]
background = '#252833'
foreground = '#FDFDFD'

[colors.cursor]
cursor = "#F2A272"
text = "#061822"

# Normal colors
[colors.normal]
black   = '#535353'#13141A'
red     = '#D21919'#F37F97
green   = '#5ADECD'
yellow  = '#F2A272'
blue    = '#8897F4'
magenta = '#C574DD'
cyan    = '#79E6F3'
white   = '#FDFDFD'

# Bright colors
[colors.bright]
black   = '#A6A6A6'#414458'
red     = '#FF4971'
green   = '#18E3C8'
yellow  = '#EBCB8B'
blue    = '#FF8037'
magenta = '#556FFF'
cyan    = '#3FDCEE'
white   = '#BEBEC1'

[colors.selection]
background = "#265b75"
text = "#BEBEC1"
