[colors]
draw_bold_text_with_bright_colors = true

#[colors.primary]
#background = "#2D2D2D"
#foreground = "#fffbf6"

[window]
decorations = "None"
dynamic_padding = true
dynamic_title = true
opacity = 0.70
startup_mode = "Maximized"
#background_opacity = 0.60

[font]
normal = { family = "CaskaydiaMono Nerd Font Mono" }
bold = { family = "CaskaydiaMono Nerd Font Mono" }
italic = { family = "CaskaydiaMono Nerd Font Mono" }
size = 11
offset = { x = 1, y = 1 }

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[cursor]
style = { shape = "Underline", blinking = "Always" }

[scrolling]
history = 1000
multiplier = 3

[selection]
save_to_clipboard = true

[general]
import = ["~/.config/alacritty/themes/thelovelace_edit.toml"]

[terminal.shell]
program = "/usr/bin/zsh"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 1
y = 1

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"
